Fix the version of more-itertools to be 5.0.0
The default version of more-itertools installed is 7.2.0 which should be latest.
While this version doesn't support python 2.7 and will get an error:
File "/usr/local/lib/python2.7/dist-packages/more_itertools/more.py", line 340
    def _collate(*iterables, key=lambda a: a, reverse=False):
                               ^
SyntaxError: invalid syntax

In order to support python2.7, it needs to be <=5.0.0.

Signed-off-by: xudan <xudan16@huawei.com>
Change-Id: I4567e0742246e2d5539cefd2d112a2022c979ca8